name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.0.2'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "github-ui-sample"
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: BUILD Docker
        run: docker build -t ${{ env.SERVICE_NAME }} .

      - name: Login to Docker Hub
        id: login-docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to Docker Hub (staging)
        env:
          IMAGE_TAG: ${{ github.event.inputs.version }}
        run: |
          docker tag $SERVICE_NAME ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$SERVICE_NAME:$IMAGE_TAG

      - name: Add Version Tag to Git
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}